name: CI
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-changes:
    runs-on: ubuntu-latest
    outputs:
        changed_files: ${{ steps.get_changed_files.outputs.changed_files }}
        env_changes: ${{ steps.get_changed_files.outputs.env_changes }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: investigate-context
        run: echo '${{ toJSON(github) }}' > github-context.json

      - name: get_changed_files
        id: get_changed_files
        run: |
          echo "changed_files=$(python get_updated.py github-context.json)" >> "$GITHUB_OUTPUT"
          echo "env_changes=$(python get_updated.py github-context.json --env)" >> "$GITHUB_OUTPUT"

      - name: print-output
        run: |
          echo $GITHUB_OUTPUT